/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CekSaldoRouteImport } from './routes/cek-saldo'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedFieldsRouteImport } from './routes/_authenticated/fields'
import { Route as AuthenticatedNfcScanRouteImport } from './routes/_authenticated/nfc-scan'
import { Route as AuthenticatedParticipantsRouteImport } from './routes/_authenticated/participants'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated/scan'
import { Route as AuthenticatedTopupRouteImport } from './routes/_authenticated/topup'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CekSaldoRoute = CekSaldoRouteImport.update({
  id: '/cek-saldo',
  path: '/cek-saldo',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFieldsRoute = AuthenticatedFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNfcScanRoute = AuthenticatedNfcScanRouteImport.update({
  id: '/nfc-scan',
  path: '/nfc-scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParticipantsRoute =
  AuthenticatedParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTopupRoute = AuthenticatedTopupRouteImport.update({
  id: '/topup',
  path: '/topup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cek-saldo': typeof CekSaldoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/events': typeof AuthenticatedEventsRoute
  '/fields': typeof AuthenticatedFieldsRoute
  '/nfc-scan': typeof AuthenticatedNfcScanRoute
  '/participants': typeof AuthenticatedParticipantsRoute
  '/products': typeof AuthenticatedProductsRoute
  '/scan': typeof AuthenticatedScanRoute
  '/topup': typeof AuthenticatedTopupRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/users': typeof AuthenticatedUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cek-saldo': typeof CekSaldoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/events': typeof AuthenticatedEventsRoute
  '/fields': typeof AuthenticatedFieldsRoute
  '/nfc-scan': typeof AuthenticatedNfcScanRoute
  '/participants': typeof AuthenticatedParticipantsRoute
  '/products': typeof AuthenticatedProductsRoute
  '/scan': typeof AuthenticatedScanRoute
  '/topup': typeof AuthenticatedTopupRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/users': typeof AuthenticatedUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cek-saldo': typeof CekSaldoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/fields': typeof AuthenticatedFieldsRoute
  '/_authenticated/nfc-scan': typeof AuthenticatedNfcScanRoute
  '/_authenticated/participants': typeof AuthenticatedParticipantsRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/scan': typeof AuthenticatedScanRoute
  '/_authenticated/topup': typeof AuthenticatedTopupRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cek-saldo'
    | '/forgot-password'
    | '/reset-password'
    | '/events'
    | '/fields'
    | '/nfc-scan'
    | '/participants'
    | '/products'
    | '/scan'
    | '/topup'
    | '/transactions'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cek-saldo'
    | '/forgot-password'
    | '/reset-password'
    | '/events'
    | '/fields'
    | '/nfc-scan'
    | '/participants'
    | '/products'
    | '/scan'
    | '/topup'
    | '/transactions'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cek-saldo'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/events'
    | '/_authenticated/fields'
    | '/_authenticated/nfc-scan'
    | '/_authenticated/participants'
    | '/_authenticated/products'
    | '/_authenticated/scan'
    | '/_authenticated/topup'
    | '/_authenticated/transactions'
    | '/_authenticated/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CekSaldoRoute: typeof CekSaldoRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cek-saldo': {
      id: '/cek-saldo'
      path: '/cek-saldo'
      fullPath: '/cek-saldo'
      preLoaderRoute: typeof CekSaldoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fields': {
      id: '/_authenticated/fields'
      path: '/fields'
      fullPath: '/fields'
      preLoaderRoute: typeof AuthenticatedFieldsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nfc-scan': {
      id: '/_authenticated/nfc-scan'
      path: '/nfc-scan'
      fullPath: '/nfc-scan'
      preLoaderRoute: typeof AuthenticatedNfcScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/participants': {
      id: '/_authenticated/participants'
      path: '/participants'
      fullPath: '/participants'
      preLoaderRoute: typeof AuthenticatedParticipantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/topup': {
      id: '/_authenticated/topup'
      path: '/topup'
      fullPath: '/topup'
      preLoaderRoute: typeof AuthenticatedTopupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedFieldsRoute: typeof AuthenticatedFieldsRoute
  AuthenticatedNfcScanRoute: typeof AuthenticatedNfcScanRoute
  AuthenticatedParticipantsRoute: typeof AuthenticatedParticipantsRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRoute
  AuthenticatedTopupRoute: typeof AuthenticatedTopupRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedFieldsRoute: AuthenticatedFieldsRoute,
  AuthenticatedNfcScanRoute: AuthenticatedNfcScanRoute,
  AuthenticatedParticipantsRoute: AuthenticatedParticipantsRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedScanRoute: AuthenticatedScanRoute,
  AuthenticatedTopupRoute: AuthenticatedTopupRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CekSaldoRoute: CekSaldoRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
